name: CI
on: [push, pull_request]
jobs:
  build:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name != github.repository)
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: msys2/setup-msys2@v2
      with:
        msystem: ucrt64
    - uses: actions/checkout@v3
    - name: Install Rust & Lua
      run: |
        pacman -S --noconfirm mingw-w64-ucrt-x86_64-rust mingw-w64-ucrt-x86_64-lua mingw-w64-ucrt-x86_64-pkgconf
    - name: Build
      run: cargo build --release --verbose
#   - name: Run tests
#     run: cargo test --verbose
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: luarunny
        path: target/release/luarunny.dll
        
